name: gym_scientific_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  fl_chart: ^0.63.0
  intl: ^0.18.1
  # CRUCIAL: Librería para el mapa del cuerpo
  path_drawing: ^1.0.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    # Rutas EXACTAS según tu estructura de carpetas subida
    - assets/images/somatotypes/Male/
    - assets/images/somatotypes/Female/
    # (El resto de imágenes del cuerpo ya no se usan porque usaremos código SVG)